In [134]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.utils import resample #para bootstraping.

In [135]:
dataset = pd.read_csv('FE_DF_Salida.csv')
dataset.head()

Unnamed: 0  State  Account length  Area code  International plan  \
0         617     47             107        408                2116   
1        1425     55              91        510                2116   
2         215     43             131        408                2116   
3        1113     47              74        408                2116   
4        2364     51             125        408                2116   

   Voice mail plan  Total day minutes  Total day calls  Total day charge  \
0              659               96.3               83             16.37   
1              659              232.4               97             39.51   
2             1674               94.4               80             16.05   
3             1674              174.1               96             29.60   
4             1674              106.1               95             18.04   

   Total eve minutes  Total eve calls  Total eve charge  Total night minutes  \
0              179.6               91             15.27                166.3   
1              186.0               88             15.81                190.5   
2              215.1              101             18.28                179.7   
3              251.1               94             21.34                257.6   
4              157.6              113             13.40                192.5   

   Total night calls  Total night charge  Total intl minutes  \
0                121                7.48                10.3   
1                128                8.57                12.3   
2                108                8.09                13.1   
3                123               11.59                 8.3   
4                 69                8.66                 8.1   

   Total intl calls  Total intl charge  Customer service calls  Churn  
0                 2               2.78                       1      0  
1                 3               3.32                       3      0  
2                 9               3.54                       2      0  
3                 5               2.24                       2      1  
4                 3               2.19                       1      0

In [136]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

from sklearn.metrics import roc_auc_score

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification

from sklearn.svm import SVC
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
from sklearn.metrics import confusion_matrix




In [137]:
X = dataset.drop(['Churn'], axis=1)
y = dataset['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=2022)

#Agregar los modelos de clasificacion (Hiperparametros)

In [138]:

lr = 'LogisticRegression().fit(X_train, y_train)'
svm = 'SVC(gamma="scale", kernel="rbf").fit(X_train, y_train)'
dt = 'DecisionTreeClassifier(criterion="gini", max_depth=4).fit(X_train, y_train)'
knn = 'KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)'
nb = 'GaussianNB().fit(X_train, y_train)'
lda = 'LinearDiscriminantAnalysis(solver="svd", store_covariance=True).fit(X_train, y_train)'
qda = 'QuadraticDiscriminantAnalysis(store_covariance=True).fit(X_train, y_train)'
rdf = 'RandomForestClassifier(n_estimators=10).fit(X_train, y_train)'
abc = 'AdaBoostClassifier(n_estimators=100).fit(X_train, y_train)'

models_list = {"lr" :lr, "svm":svm, "dt": dt,  "knn":knn, "nb":nb, "lda":lda, "qda":qda, "rdf":rdf, "abc":abc}
models_list

{'lr': 'LogisticRegression().fit(X_train, y_train)',
 'svm': 'SVC(gamma="scale", kernel="rbf").fit(X_train, y_train)',
 'dt': 'DecisionTreeClassifier(criterion="gini", max_depth=4).fit(X_train, y_train)',
 'knn': 'KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)',
 'nb': 'GaussianNB().fit(X_train, y_train)',
 'lda': 'LinearDiscriminantAnalysis(solver="svd", store_covariance=True).fit(X_train, y_train)',
 'qda': 'QuadraticDiscriminantAnalysis(store_covariance=True).fit(X_train, y_train)',
 'rdf': 'RandomForestClassifier(n_estimators=10).fit(X_train, y_train)',
 'abc': 'AdaBoostClassifier(n_estimators=100).fit(X_train, y_train)'}

## Creacion Dataset Nuevamente

In [139]:
dataset = pd.concat([X_train, y_train], axis=1)
dataset

Unnamed: 0  State  Account length  Area code  International plan  \
1594        2506     37              98        415                2116   
1766        1632     50             124        510                2116   
1921        2950     75             139        415                2116   
288          265     56              56        510                2116   
1891         619     45              62        415                2116   
...          ...    ...             ...        ...                 ...   
1713         150     37             156        415                2116   
624         2754     51             115        510                 217   
173         2554     51              61        415                2116   
1244         346     43             107        510                2116   
893         1813     50             131        408                2116   

      Voice mail plan  Total day minutes  Total day calls  Total day charge  \
1594             1674              227.1              116             38.61   
1766              659              161.2              109             27.40   
1921             1674              271.6              130             46.17   
288              1674              150.9               79             25.65   
1891             1674              245.3               91             41.70   
...               ...                ...              ...               ...   
1713             1674              178.8               94             30.40   
624              1674              345.3               81             58.70   
173              1674              188.9              105             32.11   
1244             1674              194.5               97             33.07   
893              1674              109.5               95             18.62   

      Total eve minutes  Total eve calls  Total eve charge  \
1594              120.5              103             10.24   
1766              204.2               79             17.36   
1921              156.0              131             13.26   
288               161.8               87             13.75   
1891              122.9              130             10.45   
...                 ...              ...               ...   
1713              178.4               97             15.16   
624               203.4              106             17.29   
173               153.6              116             13.06   
1244              186.3              131             15.84   
893               332.1               48             28.23   

      Total night minutes  Total night calls  Total night charge  \
1594                117.0                102                5.27   
1766                231.5                 87               10.42   
1921                136.3                108                6.13   
288                 167.7                115                7.55   
1891                228.4                102               10.28   
...                   ...                ...                 ...   
1713                169.2                 77                7.61   
624                 217.5                107                9.79   
173                 213.3                106                9.60   
1244                178.3                106                8.02   
893                 258.6                108               11.64   

      Total intl minutes  Total intl calls  Total intl charge  \
1594                 4.7                 4               1.27   
1766                 8.9                 4               2.40   
1921                11.6                 9               3.13   
288                 11.7                 5               3.16   
1891                 8.5                 4               2.30   
...                  ...               ...                ...   
1713                 7.5                 3               2.03   
624                 11.8                 8               3.19   
173                 1

### Creacion de Boost y Modelos

In [140]:
train_models_list = {}

for model_name, model in models_list.items():
    boot = resample(dataset, replace=True, n_samples=200, random_state=2020)
    X_train = boot.drop('Churn', axis = 1)
    y_train = boot.Churn
    train_model = eval(model)
    train_models_list[model_name] = train_model
    
train_models_list

c:\Users\oguti\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


{'lr': LogisticRegression(),
 'svm': SVC(),
 'dt': DecisionTreeClassifier(max_depth=4),
 'knn': KNeighborsClassifier(),
 'nb': GaussianNB(),
 'lda': LinearDiscriminantAnalysis(store_covariance=True),
 'qda': QuadraticDiscriminantAnalysis(store_covariance=True),
 'rdf': RandomForestClassifier(n_estimators=10),
 'abc': AdaBoostClassifier(n_estimators=100)}

### Realizacion de Predicciones con cada Modelo

In [141]:
auc_scores = {}
results_matrix = pd.DataFrame(columns=np.arange(0, len(y_test), 1).tolist())

for model_name, train_model in train_models_list.items():
    predicciones = train_model.predict(X_test)
    auc = roc_auc_score(y_test, predicciones)
    auc_scores[model_name] = auc
    tempDf = pd.DataFrame(predicciones).T
    results_matrix = results_matrix.append(tempDf)
    
    
    
results_matrix.index=list(train_models_list.keys())

 
results_matrix

0   1   2   3   4   5   6   7   8   9    ... 690 691 692 693 694 695 696  \
lr    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
svm   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
dt    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   1   1   
knn   0   1   0   0   0   0   0   0   0   0  ...   0   0   1   0   0   0   0   
nb    0   0   0   0   1   0   0   0   0   0  ...   0   0   0   1   0   1   1   
lda   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   1   0   0   1   
qda   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   
rdf   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   1   0   0   0   
abc   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   1   0   0   0   

    697 698 699  
lr    0   0   0  
svm   0   0   0  
dt    0   0   0  
knn   0   0   0  
nb    1   0   0  
lda   0   0   0  
qda   0   0   0  
rdf   1   0   0  
abc   1   0   0  

[9 rows x 700 columns]

## Ralizacion de Votación resultados

In [142]:
votacion = results_matrix.apply(pd.value_counts)
votacion

0    1    2    3    4    5    6    7    8    9    ...  690  691  692  693  \
0  9.0    8  9.0  9.0    8  9.0  9.0  9.0  9.0  9.0  ...  9.0  9.0    8    5   
1  NaN    1  NaN  NaN    1  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN    1    4   

   694  695  696  697  698  699  
0  9.0    7    5    6  9.0  9.0  
1  NaN    2    4    3  NaN  NaN  

[2 rows x 700 columns]

In [143]:
final_predictions = []

for (columnName, columnData) in votacion.iteritems():
    column_result = columnData.values
    final_predictions.append(np.nanargmax(column_result, axis=0))

final_predictions

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


# Roc auc

In [144]:
auc = roc_auc_score(y_test, final_predictions)
auc

0.5946969696969696

In [145]:
auc_scores


{'lr': 0.5965909090909091,
 'svm': 0.5,
 'dt': 0.6691017316017316,
 'knn': 0.4829545454545454,
 'nb': 0.650974025974026,
 'lda': 0.643668831168831,
 'qda': 0.5965909090909091,
 'rdf': 0.5984848484848485,
 'abc': 0.634469696969697}

# Hiperparametrizacion

In [146]:
svm = GridSearchCV(SVC(), {'C': [0.1, 1, 10], 'kernel': ['rbf']}, cv=5).fit(X_train, y_train)

In [147]:
svmResults = pd.DataFrame(svm.cv_results_)
svmResults.sort_values('rank_test_score', ascending=True)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.008900      0.001666         0.006915        0.001274     0.1   
1       0.011319      0.002473         0.008633        0.003064       1   
2       0.011999      0.007904         0.006774        0.003557      10   

  param_kernel                       params  split0_test_score  \
0          rbf  {'C': 0.1, 'kernel': 'rbf'}              0.775   
1          rbf    {'C': 1, 'kernel': 'rbf'}              0.775   
2          rbf   {'C': 10, 'kernel': 'rbf'}              0.750   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0              0.775              0.775              0.775              0.775   
1              0.775              0.775              0.775              0.775   
2              0.775              0.775              0.775              0.775   

   mean_test_score  std_test_score  rank_test_score  
0            0.775            0.00                1  
1            0.775            0.00                1  
2            0.770            0.01                3

In [148]:

randomForest = GridSearchCV(RandomForestClassifier(), {'n_estimators': [10]}).fit(X_train, y_train)
                                                        

In [149]:
randomForest = pd.DataFrame(randomForest.cv_results_)
randomForest.sort_values('rank_test_score', ascending=True)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.057903      0.011965         0.010679        0.005782   

  param_n_estimators                params  split0_test_score  \
0                 10  {'n_estimators': 10}              0.775   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0               0.75               0.85              0.875               0.95   

   mean_test_score  std_test_score  rank_test_score  
0             0.84        0.071764                1

In [150]:
Logistica_regresion = GridSearchCV(cv=None,
       estimator=LogisticRegression(C=1.0, intercept_scaling=1, dual=False, fit_intercept=True,
          penalty='l2', tol=0.0001),
          param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]},
       pre_dispatch='2*n_jobs', refit=True, verbose=0).fit(X_train, y_train)


c:\Users\oguti\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\oguti\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [151]:
Logistica_regresion = pd.DataFrame(Logistica_regresion.cv_results_)
Logistica_regresion.sort_values('rank_test_score', ascending=True)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
1       0.112492      0.014867         0.006467        0.002738    0.01   
4       0.130843      0.049150         0.006619        0.001414      10   
5       0.163143      0.045299         0.006928        0.002039     100   
0       0.095898      0.006104         0.008203        0.001348   0.001   
2       0.132344      0.036518         0.007141        0.002978     0.1   
3       0.096567      0.031564         0.006618        0.003423       1   
6       0.092023      0.028337         0.003649        0.000664    1000   

         params  split0_test_score  split1_test_score  split2_test_score  \
1   {'C': 0.01}              0.775              0.675              0.825   
4     {'C': 10}              0.775              0.675              0.825   
5    {'C': 100}              0.775              0.675              0.825   
0  {'C': 0.001}              0.775              0.675              0.800   
2    {'C': 0.1}              0.775              0.675              0.800   
3      {'C': 1}              0.775              0.675              0.800   
6   {'C': 1000}              0.775              0.675              0.800   

   split3_test_score  split4_test_score  mean_test_score  std_test_score  \
1               0.85              0.875            0.800        0.070711   
4               0.85              0.875            0.800        0.070711   
5               0.85              0.875            0.800        0.070711   
0               0.85              0.875            0.795        0.069642   
2               0.85              0.875            0.795        0.069642   
3               0.85              0.875            0.795        0.069642   
6               0.85              0.875            0.795        0.069642   

   rank_test_score  
1                1  
4                1  
5                1  
0                4  
2                4  
3                4  
6                4

In [152]:
Ada_Boost = AdaBoostClassifier(n_estimators=50, learning_rate=1).fit(X_train, y_train)

In [153]:
# Ada_Boost = pd.DataFrame(Ada_Boost.cv_results_)
# Ada_Boost.sort_values('rank_test_score', ascending=True)



### El modelo a utilizar es Ramdon Forest con  Roc Auc  con 0.64691 vs Hiperparametrizacion de mean_test_score 0.85

In [155]:
from sklearn.model_selection import cross_val_predict
y_train_pred = cross_val_predict(randomForest, X_train, y_train, cv=3)

TypeError: Cannot clone object '   mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.057903      0.011965         0.010679        0.005782   

  param_n_estimators                params  split0_test_score  \
0                 10  {'n_estimators': 10}              0.775   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0               0.75               0.85              0.875               0.95   

   mean_test_score  std_test_score  rank_test_score  
0             0.84        0.071764                1  ' (type <class 'pandas.core.frame.DataFrame'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' method.

In [156]:
#Create a Gaussian Classifier

randomForest = GridSearchCV(RandomForestClassifier(), {'n_estimators': [10]}).fit(X_train, y_train)
y_pred=randomForest.predict(X_test)

In [157]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8785714285714286


# Matriz de confusion

In [158]:
confusion_matrix(y_train, y_train_pred)

array([[145,  10],
       [ 25,  20]], dtype=int64)

In [159]:
y_train_perfect_predictions = y_train # pretend we reached perfection
confusion_matrix(y_train, y_train_perfect_predictions)

array([[155,   0],
       [  0,  45]], dtype=int64)

In [160]:
# Recall
from sklearn.metrics import recall_score
recall_score(y_train, y_train_pred, average=None)


array([0.93548387, 0.44444444])

In [161]:
# Precision
from sklearn.metrics import precision_score
precision_score(y_train, y_train_pred, average=None)

array([0.85294118, 0.66666667])

In [162]:
# Method 1: sklearn
from sklearn.metrics import f1_score
f1_score(y_train, y_train_pred, average=None)


array([0.89230769, 0.53333333])

In [ ]:
#ganador-> RandomForest_: n_estimators=20, max_depth=100